stages:
- name: Clone
  steps:
  - sourceCodeConfig: {}
- name: env
  steps:
  - runScriptConfig:
      image: registry.cn-hangzhou.aliyuncs.com/link-cloud/python-27-hcaas:v1.0.1
      shellScript: |-
        pwd
        ls
    env:
      MYSQL_DB_NAME: myblog
      MYSQL_HOST: mysql-service
      MYSQL_PASSWORD: root
      MYSQL_USER: root
- name: build image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: xyz:v2
      pushRemote: true
      registry: mirror.cubepaas.com/github-clz
- name: deploy mysql
  steps:
  - applyAppConfig:
      catalogTemplate: cube-global-data:library-mysql
      version: 1.3.1
      answers:
        mysqlDatabase: myblog
        mysqlPassword: root
        mysqlUser: root
      name: mysql-service
      targetNamespace: p-wgff4-pipeline
timeout: 60
notification: {}
