stages:
- name: Clone
  steps:
  - sourceCodeConfig: {}
- name: env
  steps:
  - runScriptConfig:
      image: link-cloud/python-27-hcaas:v1.0.1
      shellScript: |-
        pwd
        ls
- name: build image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: xyz:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: mirror.cubepaas.com/github-clz
- name: deploy mysql
  steps:
  - applyAppConfig:
      catalogTemplate: cube-global-data:library-mysql
      version: 1.3.1
      answers:
        mysqlDatabase: myblog
        mysqlPassword: root
        mysqlUser: root
      name: mysql-service
      targetNamespace: p-wgff4-pipeline
timeout: 60
notification: {}
