stages:
- name: Clone
  steps:
  - sourceCodeConfig: {}
- name: build image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: myblog:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: mirror.cubepaas.com/github-clz
- name: mysql
  steps:
  - applyAppConfig:
      catalogTemplate: cube-global-data:library-mysql
      version: 1.3.1
      answers:
        mysqlDatabase: myblog
        mysqlPassword: admin
        mysqlRootPassword: root
        mysqlUser: admin
      name: mysql-service
      targetNamespace: p-wgff4-pipeline
- name: web
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
