kind: Service
apiVersion: v1
metadata:
  name: myblog-service
spec:
  selector:
    app: myblog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myblog
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: myblog
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: myblog
    spec:
      containers:
      #- command:
      #  - bash
      #  - -c
      #  - /opt/app-root/src/app-trigger-file.sh
      - image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        #image: mirror.cubepaas.com/github-clz/xyz:31
        imagePullPolicy: Always
        name: myblog
        ports:
        - containerPort: 8000
          #name: 8000tcp80003
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 512Mi
      imagePullSecrets:
      - name: local-registry
